meta:
  engine: 4.1.0
units:
  # Switch spacing
  sx: 19
  sy: 19

  # Set key display size
  $default_width: 19
  $default_height: 19

  # Switch hole size
  hx: 13.8
  hy: 13.8

  # Keycap hole size (top)
  kx: 17.4
  ky: 17.4

  # Board spacing (extra padding for edges)
  bx: kx + 1.5
  by: ky + 1.5

  # external size
  ex: sx + 3.5
  ey: sy + 3.5

points:
  key:
    padding: 1sy
    spread: 1sx
  zones:
    matrix:
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        outer: 
        pinky:
        ring:
        middle:
          key.stagger: sy/4
        index:
          key.stagger: -sy/2
        inner:
      rows: 
        bottom:
        home:
        top:
    thumb:
      anchor:
        ref: matrix_outer_bottom
        shift: [0,-sy]
      columns:
        first:
          key:
            shift: [sx/4,0]
        second:
          key.shift: [sx/4,0]
          rows:
            only:
              column_net: P9
        third:
          key:
            shift: [sx,-sy/2]
        fourth:
          key.shift: [sx,-sy/2]
        fifth:
          key.shift: [sx,-sy/2]
        sixth:
          key.shift: [sx,-sy/2]
      rows:
        only:
outlines:
  keyholes:
    - what: rectangle
      where: true
      size: [hx, hy]
  keycaps:
    - what: rectangle
      where: true
      size: [kx, ky]
      corner: 2
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-bx/2, by/2]
        - ref: matrix_middle_top
          shift: [-bx/2, (by/2)-(sy/4)]
        - ref: matrix_middle_top
          shift: [-bx/2, by/2]
        - ref: matrix_middle_top
          shift: [bx/2, by/2]
        - ref: matrix_index_top
          shift: [-sx+bx/2, by/2]
        - ref: matrix_inner_top
          shift: [bx/2+sx, by/2]
        - ref: thumb_sixth_only
          shift: [bx/2, -by/2]
        - ref: thumb_third_only
          shift: [-bx/2, -by/2]
        - ref: thumb_third_only
          shift: [-bx/2, (sy/2)-(by/2)]
        - ref: thumb_first_only
          shift: [-bx/2, -by/2]
        - ref: matrix_outer_bottom
          shift: [-(bx/2)+(sx/4), -by/2]
        - ref: matrix_outer_bottom
          shift: [-bx/2, -by/2]
      fillet: 2
  outside:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-ex/2, ey/2]
        - ref: matrix_middle_top
          shift: [-ex/2, ey/2]
        - ref: matrix_middle_top
          shift: [ex/2, ey/2]
        - ref: matrix_inner_top
          shift: [ex/2+sy, ey/2]
        - ref: thumb_sixth_only
          shift: [ex/2, -ey/2]
        - ref: thumb_third_only
          shift: [-sx/2-e/2, -ey/2]
        - ref: matrix_outer_bottom
          shift: [-ex/2, -(sy + ey/2)]
      fillet: 4
  omega_plate:
    - name: board
    - operation: subtract
      name: keyholes
  omega_cover_top:
    - name: outside
    - operation: stack
      name: keycaps
    - operation: subtract
      name: keycaps
  omega_cover_side:
    - name: outside
    - operation: subtract
      name: board
    - what: circle
      radius: 1
      where: matrix_outer_top
      adjust.shift: [sx/2, -sy/2]
      operation: stack
    - what: circle
      radius: 1
      where: thumb_sixth_only
      adjust.shift: [-sx/2, sy/2]
      operation: stack
pcbs:
  omega_pcb:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: false
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -8]
      hole_top_left:
        what: mountinghole
        where: 
          ref: [matrix_outer_top]
          shift: [sx/2, -sy/2]
      hole_bottom_right:
        what: mountinghole
        where: 
          ref: [thumb_sixth_only]
          shift: [-sx/2, sy/2]
      xiao_ble:
        what: xiao_ble_smd_reversible
        where:
          ref: matrix_inner_top
          shift: [sx-0.5, -1]
          rotate: 0
      