meta:
  engine: 4.1.0
units:
  # Switch spacing
  sx: 19
  sy: 19

  # Set key display size
  $default_width: 19
  $default_height: 19

  # Switch hole size
  hx: 13.8
  hy: 13.8

  # Keycap hole size (top)
  kx: 17.4
  ky: 17.4

  # Board spacing (extra padding for edges)
  bx: kx + 2.5
  by: ky + 2.5

  # external size
  ex: sx + 3.55
  ey: sy + 3.55

points:
  key:
    padding: 1sy
    spread: 1sx
  zones:
    matrix:
      anchor.shift: [40,-80] # Fix KiCad placement
      columns:
        outer: 
          key: 
            column_net: P9
        pinky:
          key:
            column_net: P8
        ring:
          key:
            column_net: P7
        middle:
          key:
            stagger: sy/4
            column_net: P6
        index:
          key:
            stagger: -sy/2
            column_net: P5
        inner:
          key:
            column_net: P4
      rows: 
        bottom:
          row_net: P16
        home:
          row_net: P14
        top:
          row_net: P15
    thumb:
      anchor:
        ref: matrix_outer_bottom
        shift: [0,-sy]
      columns:
        first:
          key:
            shift: [sx/4,0]
            column_net: P9
        second:
          key:
            shift: [sx/4,0]
            column_net: P8
        third:
          key:
            shift: [sx,-sy/2]
            column_net: P7
        fourth:
          key:
            shift: [sx,-sy/2]
            column_net: P6
        fifth:
          key:
            shift: [sx,-sy/2]
            column_net: P5
        sixth:
          key:
            shift: [sx,-sy/2]
            column_net: P4
      rows:
        only:
          row_net: P10
outlines:
  keyholes:
    - what: rectangle
      where: true
      size: [hx, hy]
  keycaps:
    - what: rectangle
      where: true
      size: [kx, ky]
      corner: 2
  board:
    - what: polygon
      operation: stack
      asym: source
      points:
        - ref: matrix_outer_top
          shift: [-bx/2, by/2]
        - ref: matrix_middle_top
          shift: [-bx/2, (by/2)-(sy/4)]
        - ref: matrix_middle_top
          shift: [-bx/2, by/2]
        - ref: matrix_middle_top
          shift: [bx/2, by/2]
        - ref: matrix_index_top
          shift: [-sx+bx/2, by/2]
        - ref: matrix_inner_top
          shift: [sx+bx/2, by/2]
        - ref: matrix_inner_top
          shift: [sx+bx/2, -by]
        - ref: thumb_sixth_only
          shift: [bx/2, 2*bx]
        - ref: thumb_sixth_only
          shift: [bx/2, -by/2]
        - ref: thumb_third_only
          shift: [-bx/2, -by/2]
        - ref: thumb_third_only
          shift: [-bx/2, (sy/2)-(by/2)]
        - ref: thumb_first_only
          shift: [-bx/2, -by/2]
        - ref: matrix_outer_bottom
          shift: [-(bx/2)+(sx/4), -by/2]
        - ref: matrix_outer_bottom
          shift: [-bx/2, -by/2]
      fillet: 2
  outside:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-ex/2, ey/2]
        - ref: matrix_middle_top
          shift: [-ex/2, ey/2]
        - ref: matrix_middle_top
          shift: [ex/2, ey/2]
        - ref: matrix_inner_top
          shift: [ex/2+sy, ey/2]
        - ref: thumb_sixth_only
          shift: [ex/2, -ey/2]
        - ref: thumb_third_only
          shift: [-sx/2-e/2, -ey/2]
        - ref: matrix_outer_bottom
          shift: [-ex/2, -(sy + ey/2)]
      fillet: 4
  omega_plate:
    - name: board
    - operation: subtract
      name: keyholes
  omega_cover_top:
    - name: outside
    - operation: stack
      name: keycaps
    - operation: subtract
      name: keycaps
pcbs:
  omega_pcb:
    template: kicad8
    outlines:
      left:
        outline: board
    footprints:
      choc_hotswaps:
        what: ceoloide/switch_choc_v1_v2
        where: true
        adjust.rotate: 180
        params:
          side: B
          reversible: true
          hotswap: true
          #solder: true
          #hotswap_pads_same_side: true
          #include_plated_holes: true
          include_corner_marks: true
          include_choc_v1_led_cutout_marks: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      matrix_diodes:
        what: diode
        where: /matrix_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 180
          shift: [0, -9.5]
      thumb_diodes:
        what: diode
        where: /thumb_(third|fourth|fifth|sixth)_only/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 180
          shift: [0, 9]
      outside_diode:
        what: diode
        where: thumb_first_only
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: -90
          shift: [sx+15, 0]
      pinky_diode:
        what: diode
        where: thumb_second_only
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: -90
          shift: [12, 0]
      hole_top_left:
        what: ceoloide/mounting_hole_npth
        where: 
          ref: [matrix_outer_top]
          shift: [sx/2, -sy/2]
      hole_bottom_right:
        what: ceoloide/mounting_hole_npth
        where: 
          ref: [thumb_sixth_only]
          shift: [-sx/2, sy/2]
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          side: B
          reversible: true
          reverse_mount: true
        where:
          ref: matrix_inner_top
          shift: [sx, -8.1]
          rotate: 0
      nice_view:
        what: ceoloide/display_nice_view
        params:
          side: F
          reversible: true
          MOSI: P2
          SCK: P3
          CS: P1
        where:
          ref: matrix_inner_top
          shift: [sx+0.4, -11]
      jstph:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: B
          reversible: true
          BAT_P: BAT_P
          BAT_N: GND
        where:
          ref: thumb_sixth_only
          shift: [0, sy/2+15]
          rotate: 0
      on_off:
        what: ceoloide/power_switch_smd_side
        params:
          side: B
          reversible: true
          invert_behavior: false
          from: BAT_P
          to: RAW
        where:
          ref: thumb_sixth_only
          shift: [8.25, sy/2+16]
          rotate: 0
      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          side: B
          reversible: true
          from: GND
          to: RST
        where:
          ref: thumb_sixth_only
          shift: [8, sy/2+4]
          rotate: -90