meta:
  engine: 4.1.0
units:
  # Switch spacing
  sx: 19
  sy: 19

  # Set key display size
  $default_width: 19
  $default_height: 19

  # Switch hole size
  hx: 13.8
  hy: 13.8

  # Keycap hole size (top)
  kx: 17.4
  ky: 17.4

  # Board spacing (extra padding for edges)
  bx: kx + 2.5
  by: ky + 2.5

  # external size
  ex: sx + 3.55
  ey: sy + 3.55

points:
  key:
    padding: 1sy
    spread: 1sx
  zones:
    matrix:
      anchor.shift: [40,-80] # Fix KiCad placement
      columns:
        outer: 
          key: 
            column_net: P19
        pinky:
          key:
            column_net: P18
        ring:
          key:
            column_net: P15
        middle:
          key:
            stagger: sy/4
            column_net: P14
        index:
          key:
            stagger: -sy/2
            column_net: P16
        inner:
          key:
            column_net: P10
      rows: 
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
    thumb:
      anchor:
        ref: matrix_outer_bottom
        shift: [0,-sy]
      columns:
        first:
          key:
            shift: [sx/4,0]
            column_net: P19
        second:
          key:
            shift: [sx/4,0]
            column_net: P18
        third:
          key:
            shift: [sx,-sy/2]
            column_net: P15
        fourth:
          key:
            shift: [sx,-sy/2]
            column_net: P14
        fifth:
          key:
            shift: [sx,-sy/2]
            column_net: P16
        sixth:
          key:
            shift: [sx,-sy/2]
            column_net: P10
      rows:
        only:
          row_net: P9
outlines:
  keyholes:
    - what: rectangle
      where: true
      size: [hx, hy]
  keycaps:
    - what: rectangle
      where: true
      size: [kx, ky]
      corner: 2
  board:
    - what: polygon
      operation: stack
      asym: source
      points:
        - ref: matrix_outer_top
          shift: [-bx/2, by/2]
        - ref: matrix_middle_top
          shift: [-bx/2, (by/2)-(sy/4)]
        - ref: matrix_middle_top
          shift: [-bx/2, by/2]
        - ref: matrix_middle_top
          shift: [bx/2, by/2]
        - ref: matrix_index_top
          shift: [-sx+bx/2, by/2]
        - ref: matrix_inner_top
          shift: [bx/2+sx, by/2]
        - ref: thumb_sixth_only
          shift: [bx/2, -by/2]
        - ref: thumb_third_only
          shift: [-bx/2, -by/2]
        - ref: thumb_third_only
          shift: [-bx/2, (sy/2)-(by/2)]
        - ref: thumb_first_only
          shift: [-bx/2, -by/2]
        - ref: matrix_outer_bottom
          shift: [-(bx/2)+(sx/4), -by/2]
        - ref: matrix_outer_bottom
          shift: [-bx/2, -by/2]
      fillet: 2
  outside:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-ex/2, ey/2]
        - ref: matrix_middle_top
          shift: [-ex/2, ey/2]
        - ref: matrix_middle_top
          shift: [ex/2, ey/2]
        - ref: matrix_inner_top
          shift: [ex/2+sy, ey/2]
        - ref: thumb_sixth_only
          shift: [ex/2, -ey/2]
        - ref: thumb_third_only
          shift: [-sx/2-e/2, -ey/2]
        - ref: matrix_outer_bottom
          shift: [-ex/2, -(sy + ey/2)]
      fillet: 4
  omega_plate:
    - name: board
    - operation: subtract
      name: keyholes
  omega_cover_top:
    - name: outside
    - operation: stack
      name: keycaps
    - operation: subtract
      name: keycaps
pcbs:
  omega_pcb:
    outlines:
      left:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        adjust.rotate: 180
        params:
          keycaps: false
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -8.7]
      hole_top_left:
        what: mountinghole
        where: 
          ref: [matrix_outer_top]
          shift: [sx/2, -sy/2]
      hole_bottom_right:
        what: mountinghole
        where: 
          ref: [thumb_sixth_only]
          shift: [-sx/2, sy/2]
      rev_nano:
        what: rev_nano
        where:
          ref: matrix_inner_top
          shift: [sx+0.4, -8.1]
          rotate: 0
      rev_view: # Like above, lets you use the nice!vier on either side of the board
        what: niceview
        params:
          side: "F"
          reverse: true
          MOSI: P2
          SCK: P3
          CS: P1
        where:
          ref: matrix_inner_top
          shift: [sx+0.4, -10.8]
      rev_jstph: # Mainly just adds silk screen to both sides of the board to ensure proper polarity
        what: rev_jstph
        params:
          pos: BPOS
          neg: GND
        where:
          ref: thumb_sixth_only
          shift: [8, sy/2+14]
          rotate: -90
      rev_slider: # Adds a power slider to both sides of the board
        what: rev_slider
        params:
          from: BPOS
          to: RAW
        where:
          ref: thumb_sixth_only
          shift: [8, sy/2+3]
          rotate: -90
      rev_reset: # Adds a reset button to both sides of the board
        what: rev_button
        params:
          from: GND
          to: RST
        where:
          ref: thumb_sixth_only
          shift: [0, sy/2+3]
          rotate: -90
